application/post/models.py
from flask_login import current_user
from datetime import datetime




class Post:

    def __init__(self, id, title, content, date_posted = datetime.utcnow(), author = current_user):
        self.id = id
        self.title = title
        self.content = content
        self.date_posted = date_posted
        self.author =  author
    

    @classmethod
    def from_mongo(cls, mongo_doc):
        id = mongo_doc['_id']
        title = mongo_doc['title']
        content = mongo_doc['content']
        date_posted = mongo_doc['date_posted']
        author_id = mongo_doc['author']
        from application.custom import user_rep
        # Retrieve author from MongoDB 
        author = user_rep.find_user_by_id(author_id) 

        return cls(id=id, title=title, content=content, date_posted=date_posted, author=author)


    def to_mongo(self):
        return {
            '_id': self.id,
            'title': self.title,
            'content': self.content,
            'date_posted': self.date_posted,
            'author': self.author.id
        }

application/post/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from application.custom import user_rep


class PostForm(FlaskForm):
    """
    Form for creating new post.
    """
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField("Post")

application/main/routes.py
from flask import render_template, request, redirect, Blueprint, flash, url_for, current_app
from application.custom import user_rep, post_rep
from flask_login import current_user

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home", methods=['GET', 'POST'])
def home():
    """
    Route handler for the home page.

    Returns:
        str: Rendered template for the home page.
    """
    #page = request.args.get('page', 1, type=int)
    posts = post_rep.find_posts()
    following_users = []
    if current_user.is_authenticated:
        following_users = user_rep.get_following_as_list_of_users(current_user)

    return render_template("home.html", title="Home", posts=posts, following_users=following_users)


@main.route("/about")
def about():
    """
    Route handler for the about page.

    Returns:
        str: Rendered template for the about page.
    """
    return render_template("about.html", title="About")


@main.route("/search", methods=['GET', 'POST'])
def search():
    """
    Route handler for the search page.

    Returns:
        str: Rendered template for the search page.
    """
    if request.method == 'POST':
        query = request.form.get('search_input')
    else:
        query = request.args.get('query')

    posts = post_rep.search_posts(query)
    users = user_rep.search_users(query)
    return render_template("search_results.html", title="Search", posts=posts, users=users, query=query)

application/post/routes.py
from flask import Blueprint, flash, redirect, url_for, render_template, request, abort
from .forms import PostForm
from application.custom import post_rep
from flask_login import current_user, login_required

post = Blueprint('post', __name__)


@post.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post_rep.insert_post(title=form.title.data, content=form.content.data)
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    
    return render_template('new_post.html', title='New Post', form=form, legend='New Post')


@post.route("/post/<int:post_id>")
def post_page(post_id):
    post = post_rep.find_post_by_id(post_id)
    return render_template('post.html', title=post.title, post=post)


@post.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = post_rep.find_post_by_id(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post_rep.update_post(post=post, title=form.title.data, content=form.content.data)
        flash('Your post has been updated!', 'success')
        return redirect(url_for('post.post_page', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('new_post.html', title='Update Post',
                           form=form, legend='Update Post')

@post.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = post_rep.find_post_by_id(post_id)
    if post.author != current_user:
        abort(403)
    post_rep.delete_post(post=post)
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))


'''

@post.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)
'''

application/tasks/routes.py
from flask import render_template, request, redirect, Blueprint, flash, url_for, current_app, jsonify
from application.custom import user_rep, post_rep
from flask_login import login_required, current_user

tasks = Blueprint('tasks', __name__)


@tasks.route("/my_tasks")
@login_required
def my_tasks():
    """
    Route handler for the tasks page.

    Returns:
        str: Rendered template for the tasks page.
    """

    tasks = user_rep.find_tasks_by_user_id(current_user)

    return render_template("my_tasks.html", title="Tasks", tasks=tasks)


@tasks.route("/add_task", methods=['POST'])
@login_required
def add_task():
    """
    Route handler for the tasks page.

    Returns:
        str: Rendered template for the tasks page.
    """
    data  = request.get_json()
    user_rep.add_task_by_user_id(current_user, data['description'])
    result = {"success": True, "response": "Done"}
    return jsonify(result)


@tasks.route("/edit/<int:task_id>", methods=['POST'])
def update(task_id):
    """ recieved post requests for entry updates """

    data = request.get_json()

    try:
        if "status" in data:
            user_rep.update_task_status(task_id ,current_user, data["status"])
            result = {'success': True, 'response': 'Status Updated'}
        elif "description" in data:
            user_rep.update_task_description(task_id, current_user, data["description"])
            result = {'success': True, 'response': 'Task Updated'}
        else:
            result = {'success': True, 'response': 'Nothing Updated'}
    except:
        result = {'success': False, 'response': 'Something went wrong'}

    return jsonify(result)


@tasks.route("/delete/<int:task_id>", methods=['POST'])
def delete(task_id):
    """ recieved post requests for entry updates """
    try:
        user_rep.delete_task_from_user_by_id(current_user, task_id)
        result = {'success': True, 'response': 'Task Deleted'}
    except:
        result = {'success': False, 'response': 'Something went wrong'}

    return jsonify(result)

application/users/routes.py
from flask import Blueprint

from flask import render_template, request, redirect, Blueprint, flash, url_for, jsonify
from application import bcrypt, login_manager
from .forms import RegistrationForm, LoginForm, UpdateAccountForm
from application.custom import user_rep, post_rep
from flask_login import login_user, current_user, logout_user, login_required
from .utils import save_picture
from .models import User

users = Blueprint('users', __name__)



@login_manager.user_loader
def load_user(user_id):
    """
    Callback function for Flask-Login to load a user from user ID.

    Args:
        user_id (int): The ID of the user to load.

    Returns:
        User: The User object associated with the user ID.
    """
    return user_rep.find_user_by_id(user_id)


@users.route("/register", methods=["GET", "POST"])
def register():
    """
    Route handler for user registration.

    If the user is already authenticated, they are redirected to the home page.
    If the registration form is submitted and valid, the user is registered, a success message 
    is flashed, and they are redirected to the login page.

    Returns:
        str: Rendered template for the registration page or redirect response.
    """
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user_rep.register_user(username=form.username.data, password=hashed_password, email=form.email.data)
        flash(f"Your account has been created! You are now able to log in", category="success")
        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    """
    Route handler for user login.

    If the user is already authenticated, they are redirected to the home page.
    If the login form is submitted and valid, the user is logged in, a success message is flashed, 
    and they are redirected to the home page.

    Returns:
        str: Rendered template for the login page or redirect response.
    """
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = LoginForm()
    if form.validate_on_submit():
        user = user_rep.find_user_by_email(email=form.email.data)
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash("You have been logged in!", category="success")
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login unsuccessful. Please check email and password", category="danger")

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))



@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
            user_rep.update_user_image(current_user)

        current_user.email = form.email.data
        current_user.username = form.username.data

        user_rep.update_user_username(current_user)
        user_rep.update_user_email(current_user)

        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)

    posts = post_rep.find_posts_by_author(current_user.id)
    following_users = user_rep.get_following_as_list_of_users(current_user)

    return render_template('account.html', title='Account',
                           image_file=image_file, 
                           form=form, 
                           posts=posts,
                           following_users=following_users)


@users.route("/user/<int:user_id>")
def user_profile(user_id):
    try:
        if current_user.id == user_id:
            return redirect(url_for('users.account'))
    except:
        print("something went wrong")
    
    posts = post_rep.find_posts_by_author(user_id)
    user = user_rep.find_user_by_id(user_id)
    username = user.username
    email = user.email
    image_file = user.image_file

    is_following = current_user.id in user.followers

    return render_template('user_profile.html', title=username,
                            image_file=image_file, 
                            posts=posts,
                            username=username,
                            email=email,
                            user_id=user_id,
                            is_following=is_following)


@users.route("/follow/<int:user_id>", methods=["POST", "GET"])
@login_required
def follow(user_id):
    target = user_rep.find_user_by_id(user_id)
    if not target:
        return jsonify({'error': 'User not found'}), 404
    #target_user = User(target)
    current_user.follow(target)
    return jsonify({'message': f'You are now following {target.username}'}), 200

@users.route('/unfollow/<int:user_id>', methods=['POST', "GET"])
@login_required
def unfollow(user_id):
    target = user_rep.find_user_by_id(user_id)
    if not target:
        return jsonify({'error': 'User not found'}), 404
    #target_user = User(target)
    current_user.unfollow(target)
    return jsonify({'message': f'You have unfollowed {target.username}'}), 200

application/templates/about.html
{% extends "base.html" %}

{% block content %}
<div>
  ABOUT
</div>
{% endblock content %}

application/templates/account.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group mt-4">
                    {{ form.username.label(class="form-control-label mb-2") }} :
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group mt-4">
                    {{ form.email.label(class="form-control-label mb-2") }} :
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group mt-4">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group mt-4">
                {{ form.submit(class="btn btn-outline-success") }}
            </div>
        </form>
    </div>

    <div class="content-section">
        {%if posts%}
            {% for post in posts %}
            <article class="media content-section article-section" style="display: flex; justify-content: left;">
                <img class="rounded-circle article-img " style="height: 66px; width: 66px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                <div class="media-body">
                    <div class="article-metadata mt-3 mb-2">
                        <a class="mr-4" href="#"> @{{ post.author.username }} </a>
                        <small class="text-muted" style="margin-left: 5px;">{{ post.date_posted.strftime('%d.%m.%Y, %H:%M') }}</small>
                    </div>
                    <h2><a class="article-title" href="{{ url_for('post.post_page', post_id=post.id) }}">{{ post.title }}</a></h2>
                    <p class="article-content">{{ post.content }}</p>
                    
                </div>
            </article>
            {% endfor %}
        {% endif %}
    </div>
{% endblock content %}

{% block rightcontent%} 
    <div class="content-section following-list">
        <div class="following-list-title">
            You are following:
        </div>

        {% for user in following_users %}
        <div class="following-entry">
            <img src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}" alt="{{ user.username }}" class="following-img">
            <a href="{{ url_for('users.user_profile', user_id=user.id) }}" class="following-name">{{ user.username }}</a>
        </div>
        {% endfor %}
    </div>
{% endblock rightcontent %}

application/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous">
    <link rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}">
    {% if title %}
    <title>UniAssist - {{ title }} </title>
    {% else %}
    <title>UniAssist - Base </title>
    {% endif %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/katex.min.css" 
          integrity="sha384-D+9gmBxUQogRLqvARvNLmA9hS2x//eK1FhVb9PiU86gmcrBrJAQT8okdJ4LMp2uv" 
          crossorigin="anonymous">
    <!-- The loading of KaTeX is deferred to speed up page rendering -->
    <script src="https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/katex.min.js" 
            integrity="sha384-483A6DwYfKeDa0Q52fJmxFXkcPCFfnXMoXblOkJ4JcA8zATN6Tm78UNL72AKk+0O" 
            crossorigin="anonymous"></script>
    <!-- To automatically render math in text elements, include the auto-render extension: -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/contrib/auto-render.min.js" integrity="sha384-yACMu8JWxKzSp/C1YV86pzGiQ/l1YUfE8oPuahJQxzehAjEt2GiQuy/BIvl9KyeF" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>   
    <!--<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
     script used for bringing icons from fronawsome website -->
    <script src="https://kit.fontawesome.com/ad2f0887b8.js"
      crossorigin="anonymous"></script>

    <script
      src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"></script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
      integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
      crossorigin="anonymous"></script>
        
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"></script>

  </head>
  <body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container" >
              <div>
                <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">UniAssist</a>
              </div>
              
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                  aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle" style="display: flex; justify-content: space-between;">
                  <div class="navbar-nav">
                    <div class="search-bar">
                      <form method="POST" action="{{ url_for('main.search') }}" onsubmit="return validateForm()">
                          <div class="input-group" style="border-radius: 30px 0 0 30px; border-right: none;">
                              <input id="search_input" type="text" class="form-control" placeholder="Search ..." name="search_input"
                                  aria-label="Search" style="border-radius: 30px 0 0 30px; border-right: none;">
                              <div class="input-group-append" style="margin-left: -2px; border-radius: 0 30px 30px 0; background-color: #ffffff; color: #333; border-left: none;">
                                  <button type="submit" class="btn"
                                      style="border-radius: 0 30px 30px 0; background-color: #ffffff; color: #333; border-left: none;">
                                      <i class="fa fa-search" style="margin-top: 12px;"></i>
                                  </button>
                              </div>
                          </div>
                          <script>
                              // Clear search input when focused
                              document.getElementById("search_input").addEventListener("focus", function () {
                                  document.getElementById("search_input").value = "";
                              });
                              function validateForm() {
                                    var searchInput = document.getElementById("search_input").value.trim();
                                    if (searchInput === "") {      
                                        return false; // Prevent form submission
                                    }
                                    return true; // Allow form submission
                                }
                          </script>
                      </form>
                  </div>
                  </div>
                  <div class="navbar-nav" style="align-content: center;">
                      <!-- Navbar Right Side -->
                      {% if current_user.is_authenticated == False %}
                      <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                      <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                      {% else %}
                      <div class="dropdown ml-auto" style="margin-top: 10px;">
                          <a class="nav-item nav-link" href="#">
                            <div >
                              <i class="fa fa-plus fa-2xl" style="color: #ffffff;"></i>
                          </div>
                          </a>
                          <div class="dropdown-content ml-auto">
                              <a href="{{ url_for('post.new_post')}}">Add Article</a>
                              <a href="#">Add Something</a>
                          </div>
                      </div>
                      <div class="dropdown">
                          <a class="nav-item nav-link" href="#">
                              <img class="rounded-circle nav-img"
                                  src="{{ url_for('static', filename='profile_pics/' + current_user.image_file )}}">
                          </a>
                          <div class="dropdown-content">
                              <a href="{{ url_for('users.account') }}">Profile</a>
                              <a href="{{ url_for('users.logout') }}">Logout</a>
                              <a href="https://www.youtube.com/user/hubspot">YouTube</a>
                          </div>
                      </div>
                      {% endif %}
                  </div>
              </div>
          </div>
      </nav>
  </header>
  
  
  
  

    <div class="area" >
      <nav class="main-menu" style="position: fixed;">
        <ul>
          <li>
            <a href="{{ url_for('main.home') }}">
              <!-- <i class="fa fa-home fa-2x"></i> -->
              <i class="fa fa-solid fa-house fa-2x"></i>
              <span class="nav-text">
                Home
              </span>
            </a>

          </li>
          <li class="has-subnav">
            <a href="#">
              <!-- <i class="fa fa-globe fa-2x"></i> -->
              <i class="fa fa-solid fa-note-sticky fa-2x"></i>

              <span class="nav-text">
                Notes
              </span>
            </a>

          </li>
          <li class="has-subnav">
            <a href="{{ url_for('tasks.my_tasks') }}">
              <!-- <i class="fa fa-comments fa-2x"></i> -->
              <i class="fa fa-solid fa-list-check fa-2x"></i>
              <span class="nav-text">
                Tasks
              </span>
            </a>

          </li>
          <li class="has-subnav">
            <a href="#">
              <i class="fa fa-solid fa-school fa-2x"></i>
              <span class="nav-text">
                Student space
              </span>
            </a>

          </li>
          <!-- <li>
                    <a href="#">
                        <i class="fa fa-film fa-2x"></i>
                        <span class="nav-text">
                            Not Ready
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-book fa-2x"></i>
                        <span class="nav-text">
                            Not Ready
                        </span>
                    </a>
                </li> -->
          <li>
            <a href="#">
              <i class="fa fa-cogs fa-2x"></i>
              <span class="nav-text">
                Settings
              </span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-map-marker fa-2x"></i>
              <span class="nav-text">
                Locations
              </span>
            </a>
          </li>
          <li>
            <a href="{{ url_for('main.about') }}">
              <i class="fa fa-info fa-2x"></i>
              <span class="nav-text">
                About
              </span>
            </a>
          </li>
        </ul>

        <ul class="logout">
          <li>
            <a href="#">
              <i class="fa fa-power-off fa-2x"></i>
              <span class="nav-text">
                Logout
              </span>
            </a>
          </li>
        </ul>
      </nav>
    </div>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}
        
        </div>
      </div>

      <div class="row main-container">
        <div class="col-md-8 content">
          {% block content %}{% endblock %}
        </div>
        <div class="right-container">
          {% block rightcontent %} {% endblock %}
        </div>
      </div>
    </main>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
  </body>
</html>

application/templates/post.html
{% extends "base.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_profile', user_id=post.author.id) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%d.%m.%Y') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('post.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Are you sure want to delete this article ?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <form action="{{ url_for('post.delete_post', post_id=post.id) }}" method="POST">
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

application/templates/search_results.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <h3>Search Results For: {{ query }}</h3>
    </div>
    {% if users %}
        <h3> Users: </h3>
        {% for user in users %}
            <div class="content-section">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}">
                <a href="{{ url_for('users.user_profile', user_id=user.id) }}">{{ user.username }}</a>
            </div>
        {% endfor %}
    {% endif %}

    {% if posts %}
        <h3> Posts: </h3>
        {% for post in posts %}
            <div class="content-section">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                <a href="{{ url_for('post.post_page', post_id=post.id) }}">{{ post.title }}</a>
            </div>
        {% endfor %}
    {% endif %}

{% endblock content %}